Updated Github Workflows

diff --git a/.github/workflows/dev.yml b/.github/workflows/dev.yml
--- a/.github/workflows/dev.yml
+++ b/.github/workflows/dev.yml
@@ -1,48 +1,67 @@
-name: Deploy to dev Server
+name: 'Deploy to Server'
+
 on:
- push:
-  branches:
-    - dev
+  push:
+    branches: ['dev']
 
 jobs:
   build-and-deploy:
     runs-on: ubuntu-latest
+    environment: 
+      name: ${{ github.ref_name }}
 
     steps:
     - name: Checkout code
-      uses: actions/checkout@v2
-
-    - name: Install SSH and SSHPass
-      run: |
-        sudo apt-get update
-        sudo apt-get install -y sshpass openssh-client
-
-    - name: Set up SSH key
-      run: |
-        mkdir -p ~/.ssh
-        echo "${{secrets.SSH_PRIVATE_KEY_NODE_DEV}}" > ~/.ssh/id_rsa
-        chmod 600 ~/.ssh/id_rsa
-
-    - name: Extract repo name
-      id: extract-repo-name
-      run: |
-        REPO_NAME=$(basename ${{github.repository}})
-        echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
-
-    - name: Copy deploy_dev_script.sh to EC2
+      uses: actions/checkout@v3
+    - name: Build & Deploy
+      uses: appleboy/ssh-action@v1.0.3 
       env:
-        EC2_HOST: 100.26.200.255
-        EC2_USER: ec2-user
-      run: |
-        ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts
-        scp -o StrictHostKeyChecking=no ./deploy_dev_script.sh $EC2_USER@$EC2_HOST:/home/$EC2_USER/
+        REPO_NAME: ${{ github.repository }}
+        BRANCH_NAME: ${{ github.ref_name }}
+      with:
+          host: 100.26.200.255
+          username: "ec2-user"
+          key: ${{ secrets.SSH_PRIVATE_KEY }}
+          port: ${{ secrets.PORT }}
+          envs: REPO_NAME,BRANCH_NAME
+          script: |
+            echo "REPO_NAME: $REPO_NAME"
+            echo "branch_name: $BRANCH_NAME"
+            echo "GITHUB_SHA: $GITHUB_SHA"
+            GITHUB_SHA="${{ github.sha }}"
+            REPOS_NAME=$(echo "$REPO_NAME" | cut -d'/' -f2)
+            CONTAINER_NAME="${REPOS_NAME}"
+            echo "REPOS_NAME: $REPOS_NAME"
+            ENV="${BRANCH_NAME}"
+            if [[ ! -d "$REPOS_NAME" ]]; then
+              git clone git@github.com:DaffiDigital/DaffiOne-Backend-V3.git -b "$BRANCH_NAME" "$REPOS_NAME"
+              cd "$REPOS_NAME"
+            else
+              cd "$REPOS_NAME"
+              git pull origin "$BRANCH_NAME"
+            fi
+            GIT_HASH=$(git rev-parse --short "$GITHUB_SHA")
+            echo "GIT_HASH=$GIT_HASH"
+            IMAGE_NAME="$(echo "${REPOS_NAME}:${GIT_HASH}" | tr '[:upper:]' '[:lower:]')"
+            if [ $? -eq 0 ]; then
+              sudo docker build --build-arg ENV="$ENV" -t "$IMAGE_NAME" .
+              if [ $? -eq 0 ]; then
+                if docker ps -a --format '{{.Names}}' | grep -Eq "^$CONTAINER_NAME$"; then
+                  echo "Stopping existing container: $CONTAINER_NAME"
+                  sudo docker stop "$CONTAINER_NAME" || true
+                  echo "Removing existing container: $CONTAINER_NAME"
+                  sudo docker rm "$CONTAINER_NAME" || true
+                else
+                  echo "docker container stop failed or container not exists"
+                fi  
+              else
+                echo "Docker build failed."
+                exit 1
+              fi
+            else
+              echo "Git operation failed."
+              exit 1
+            fi
+            sudo docker run -d --network=daffione -p 3001:3000 --name "$CONTAINER_NAME" "$IMAGE_NAME"
+            sudo docker image prune -a -f || true
 
-    - name: Execute deploy_dev_script.sh on EC2
-      env:
-        EC2_HOST: 100.26.200.255
-        EC2_USER: ec2-user
-        REPO_SLUG: ${{env.REPO_NAME}}
-        COMMIT_HASH: ${{github.sha}}
-        BRANCH: ${{github.ref_name}}
-      run: |
-        ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST "bash /home/$EC2_USER/deploy_dev_script.sh $REPO_SLUG ${COMMIT_HASH:0:7} $BRANCH"
